
server:
  port: 8888
logging:
  path: logs
  file: userManager.log
spring:
  application:
    name: userManager.log
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.63:3306/test
    username: root
    password: 123

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*

